/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as EbooksIndexRouteImport } from './routes/ebooks/index'
import { Route as EbooksSlugRouteImport } from './routes/ebooks/$slug'
import { Route as PlacesIndexRouteImport } from './routes/places/index'
import { Route as PlacesSlugRouteImport } from './routes/places/$slug'
import { Route as PoetryIndexRouteImport } from './routes/poetry/index'
import { Route as PoetryIdRouteImport } from './routes/poetry/$id'
import { Route as PoetsIndexRouteImport } from './routes/poets/index'
import { Route as PoetsSlugRouteImport } from './routes/poets/$slug'
import { Route as QawwaliIndexRouteImport } from './routes/qawwali/index'
import { Route as QawwaliIdRouteImport } from './routes/qawwali/$id'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as StoriesSlugRouteImport } from './routes/stories/$slug'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as TermsSlugRouteImport } from './routes/terms/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksIndexRoute = EbooksIndexRouteImport.update({
  id: '/ebooks/',
  path: '/ebooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const EbooksSlugRoute = EbooksSlugRouteImport.update({
  id: '/ebooks/$slug',
  path: '/ebooks/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesIndexRoute = PlacesIndexRouteImport.update({
  id: '/places/',
  path: '/places/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesSlugRoute = PlacesSlugRouteImport.update({
  id: '/places/$slug',
  path: '/places/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryIndexRoute = PoetryIndexRouteImport.update({
  id: '/poetry/',
  path: '/poetry/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryIdRoute = PoetryIdRouteImport.update({
  id: '/poetry/$id',
  path: '/poetry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetsIndexRoute = PoetsIndexRouteImport.update({
  id: '/poets/',
  path: '/poets/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetsSlugRoute = PoetsSlugRouteImport.update({
  id: '/poets/$slug',
  path: '/poets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const QawwaliIndexRoute = QawwaliIndexRouteImport.update({
  id: '/qawwali/',
  path: '/qawwali/',
  getParentRoute: () => rootRouteImport,
} as any)
const QawwaliIdRoute = QawwaliIdRouteImport.update({
  id: '/qawwali/$id',
  path: '/qawwali/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsSlugRoute = TermsSlugRouteImport.update({
  id: '/terms/$slug',
  path: '/terms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/quotes': typeof QuotesRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/poetry/$id': typeof PoetryIdRoute
  '/poets/$slug': typeof PoetsSlugRoute
  '/qawwali/$id': typeof QawwaliIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/terms/$slug': typeof TermsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/poetry/': typeof PoetryIndexRoute
  '/poets/': typeof PoetsIndexRoute
  '/qawwali/': typeof QawwaliIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/quotes': typeof QuotesRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/poetry/$id': typeof PoetryIdRoute
  '/poets/$slug': typeof PoetsSlugRoute
  '/qawwali/$id': typeof QawwaliIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/terms/$slug': typeof TermsSlugRoute
  '/articles': typeof ArticlesIndexRoute
  '/ebooks': typeof EbooksIndexRoute
  '/places': typeof PlacesIndexRoute
  '/poetry': typeof PoetryIndexRoute
  '/poets': typeof PoetsIndexRoute
  '/qawwali': typeof QawwaliIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/terms': typeof TermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/favorites': typeof FavoritesRoute
  '/quotes': typeof QuotesRoute
  '/search': typeof SearchRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/ebooks/$slug': typeof EbooksSlugRoute
  '/places/$slug': typeof PlacesSlugRoute
  '/poetry/$id': typeof PoetryIdRoute
  '/poets/$slug': typeof PoetsSlugRoute
  '/qawwali/$id': typeof QawwaliIdRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/terms/$slug': typeof TermsSlugRoute
  '/articles/': typeof ArticlesIndexRoute
  '/ebooks/': typeof EbooksIndexRoute
  '/places/': typeof PlacesIndexRoute
  '/poetry/': typeof PoetryIndexRoute
  '/poets/': typeof PoetsIndexRoute
  '/qawwali/': typeof QawwaliIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/terms/': typeof TermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/favorites'
    | '/quotes'
    | '/search'
    | '/articles/$slug'
    | '/ebooks/$slug'
    | '/places/$slug'
    | '/poetry/$id'
    | '/poets/$slug'
    | '/qawwali/$id'
    | '/stories/$slug'
    | '/terms/$slug'
    | '/articles/'
    | '/ebooks/'
    | '/places/'
    | '/poetry/'
    | '/poets/'
    | '/qawwali/'
    | '/stories/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/favorites'
    | '/quotes'
    | '/search'
    | '/articles/$slug'
    | '/ebooks/$slug'
    | '/places/$slug'
    | '/poetry/$id'
    | '/poets/$slug'
    | '/qawwali/$id'
    | '/stories/$slug'
    | '/terms/$slug'
    | '/articles'
    | '/ebooks'
    | '/places'
    | '/poetry'
    | '/poets'
    | '/qawwali'
    | '/stories'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/favorites'
    | '/quotes'
    | '/search'
    | '/articles/$slug'
    | '/ebooks/$slug'
    | '/places/$slug'
    | '/poetry/$id'
    | '/poets/$slug'
    | '/qawwali/$id'
    | '/stories/$slug'
    | '/terms/$slug'
    | '/articles/'
    | '/ebooks/'
    | '/places/'
    | '/poetry/'
    | '/poets/'
    | '/qawwali/'
    | '/stories/'
    | '/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  FavoritesRoute: typeof FavoritesRoute
  QuotesRoute: typeof QuotesRoute
  SearchRoute: typeof SearchRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  EbooksSlugRoute: typeof EbooksSlugRoute
  PlacesSlugRoute: typeof PlacesSlugRoute
  PoetryIdRoute: typeof PoetryIdRoute
  PoetsSlugRoute: typeof PoetsSlugRoute
  QawwaliIdRoute: typeof QawwaliIdRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
  TermsSlugRoute: typeof TermsSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  EbooksIndexRoute: typeof EbooksIndexRoute
  PlacesIndexRoute: typeof PlacesIndexRoute
  PoetryIndexRoute: typeof PoetryIndexRoute
  PoetsIndexRoute: typeof PoetsIndexRoute
  QawwaliIndexRoute: typeof QawwaliIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/': {
      id: '/ebooks/'
      path: '/ebooks'
      fullPath: '/ebooks/'
      preLoaderRoute: typeof EbooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebooks/$slug': {
      id: '/ebooks/$slug'
      path: '/ebooks/$slug'
      fullPath: '/ebooks/$slug'
      preLoaderRoute: typeof EbooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/': {
      id: '/places/'
      path: '/places'
      fullPath: '/places/'
      preLoaderRoute: typeof PlacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$slug': {
      id: '/places/$slug'
      path: '/places/$slug'
      fullPath: '/places/$slug'
      preLoaderRoute: typeof PlacesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry/': {
      id: '/poetry/'
      path: '/poetry'
      fullPath: '/poetry/'
      preLoaderRoute: typeof PoetryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry/$id': {
      id: '/poetry/$id'
      path: '/poetry/$id'
      fullPath: '/poetry/$id'
      preLoaderRoute: typeof PoetryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poets/': {
      id: '/poets/'
      path: '/poets'
      fullPath: '/poets/'
      preLoaderRoute: typeof PoetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poets/$slug': {
      id: '/poets/$slug'
      path: '/poets/$slug'
      fullPath: '/poets/$slug'
      preLoaderRoute: typeof PoetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qawwali/': {
      id: '/qawwali/'
      path: '/qawwali'
      fullPath: '/qawwali/'
      preLoaderRoute: typeof QawwaliIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qawwali/$id': {
      id: '/qawwali/$id'
      path: '/qawwali/$id'
      fullPath: '/qawwali/$id'
      preLoaderRoute: typeof QawwaliIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/$slug': {
      id: '/terms/$slug'
      path: '/terms/$slug'
      fullPath: '/terms/$slug'
      preLoaderRoute: typeof TermsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  FavoritesRoute: FavoritesRoute,
  QuotesRoute: QuotesRoute,
  SearchRoute: SearchRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  EbooksSlugRoute: EbooksSlugRoute,
  PlacesSlugRoute: PlacesSlugRoute,
  PoetryIdRoute: PoetryIdRoute,
  PoetsSlugRoute: PoetsSlugRoute,
  QawwaliIdRoute: QawwaliIdRoute,
  StoriesSlugRoute: StoriesSlugRoute,
  TermsSlugRoute: TermsSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  EbooksIndexRoute: EbooksIndexRoute,
  PlacesIndexRoute: PlacesIndexRoute,
  PoetryIndexRoute: PoetryIndexRoute,
  PoetsIndexRoute: PoetsIndexRoute,
  QawwaliIndexRoute: QawwaliIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
